title: "Carlos Figueroa"
description: >- 
  Data Science Portfolio - Projects, Resume and Skills.
show_downloads: true
# Theme
theme: jekyll-theme-minimal


#favicon: /assets/img/profile.jpg
logo: /assets/img/favicon.png
